### ISSUE TITLE
Page doesn't display due to PHP errors

### ISSUE THREAD

**Issue by Kupac** [fulxie/RefFinder#2]
Hello!
I tested it, but nothing is displayed. 
Please, is there another link? That would help me a lot...

Thank you so much!

_Originally posted by @Tharynr in https://github.com/fulxie/RefFinder/issues/1#issuecomment-456898334_

**Comment by Kupac** [comment]
Hi! This was posted by @Tharynr in another thread. I also had this problem, and it was solved by looking at the apache log, and adding/modifying the necessary files:
1. Added PHPExcel/Autoloader.php
2. Commented out a `break;` statement in  class/Functions (line 565)

**Comment by Tharynr** [comment]
Hi, Kupac!
Thanks for your answer! In fact, I'm a begginer in this field (Bioinformatics). 
Please, could you explain step by step? How to run the site on my computer? 
I really need to use RefFinder...

Thanks!

**Comment by fulxie** [comment]
Sorry for the late reply.
I will test it again tonight and will update you guys!

Thanks,

Fuliang

**Comment by fulxie** [comment]
High-version PHP doesn't tolerate the original syntax of PHPExcel and caused display failure. 
`	} elseif(is_array($value)) {
				return 64;
				break;
`

I have fixed it and also tested it on xampp(v3.2.2, PHP 7.3.1). 
reference.php was renamed to index.php

**Comment by Tharynr** [comment]
Hi Fuliang,
Thanks a lot for your help and attention!

I tested it and now it's different. The page RefFinder appears, but it doesn't run the data.
I tried to analyze the example and this message appeared: "Not Found
The requested URL /RefFinder-master/type=reference was not found on this server."
How do I proceed?

Thanks!

**Comment by fulxie** [comment]
@Tharynr ,
An old file was uploaded this morning. I replaced it . Please try it again

**Comment by Tharynr** [comment]
I tried again and now it's ok!! 

Thank you so much!!

**Comment by ndhnscc** [comment]
Hi,
the page is still not working using any links. what to do about it?
Thanks..

**Comment by NonieRodgers** [comment]
Hi,

I've just tried to download too and the website won't let me in, saying "localhost refused to connect". Any ideas on how to fix this? 

Thanks!
